### ISSUE TITLE
Spatial Deconvolution of image-based data

### ISSUE THREAD

**Issue by alexdray86** [saeyslab/spotless-benchmark#3]
Dear all,

I discovered this github thanks to a poster seen at the SCG conference in Utrecht. It is very useful to me as I am developing myself a deconvolution method that I wanted to compare with standard published methods. 

I could see that the synthetic data you provide seems to be visium-like spatial data. Do you have any equivalent synthetic data that would look more like image-based spatial transcriptomic data ?

Thanks in advance, 

Best,

Alexandre Coudray
PhD Student at EPFL Lausanne Switzerland 
Trono / La Manno research group

**Comment by csangara** [comment]
Hello, thanks for your interest in our pipeline!

I think I need a bit more clarification: by image-based-like data, do you mean data that is at single-cell resolution? 

Because we do have two datasets in [standards.tar.gz](https://zenodo.org/record/6786528/#.Y1k13HbP1PY) called gold_standard_1 and _2 that was made from [seqFISH+ data](https://www.nature.com/articles/s41586-019-1049-y). But here, we aggregated counts from all cells that belong to the same 55-μm spot diameter so I'm not sure if that's what you wanted.
