### ISSUE TITLE
Memory problem with a failed run 

### ISSUE THREAD

**Issue by alexdray86** [saeyslab/spotless-benchmark#4]
Hey again, 

I allow myself to also post a problem I had. I tried running the benchmarking with all methods on my laptop, which was probably not a good idea. It used more than 200Gb of my disk memory before throwing error message that seem linked to a lack of memory. Unfortunately my computer crashed and I don't have the error messages.

Now the problem is that I cannot locate these 200Gb of memory used by your pipeline. I used nextflow with Docker. Any idea where this pipeline is storing the intermediate files / cache ? I could see it was running 8 jobs in parallel and I guess the issue came from the duplication of scRNA matrix - which are probably stored somewhere on my computer but cannot find it ! 

Thanks in advance. Best, 

Alex C. from EPFL

**Comment by csangara** [comment]
Oh no... Indeed, running multiple methods is only recommended for on a server/cluster. I will add this to the README, sorry about that!

### Memory Issue
The memory issue might be because the containers still have to be downloaded. Nextflow uses symbolic links to a file instead of duplicating it, so I don't think duplication of the matrices is a problem.

Can you try downloading the containers locally first? You can use something like this (might take a while if you download all of them though):
```
for method in cell2location destvi dstg music nnls rctd spatialdwls spotlight stereoscope stride seurat tangram
do
docker pull csangara/sp_${method}:latest
done

docker pull csangara/sp_eval:latest # for computing performance metrics
docker pull csangara/seuratdisk:latest # for converting between Seurat and AnnData objects internally
```

### Intermediate files
Nextflow stores intermediate files inside the `work/` directory (you can configure this in `workDir` the file `nextflow.config`). For instance, if you run NNLS with the test data

```
nextflow run main.nf -profile local,docker --annot subclass --methods nnls \
--rootdir /mnt/d/spotless-benchmark #full directory to repo folder
```

You will get something like this in the terminal
```
N E X T F L O W  ~  version 21.04.3
Launching `main.nf` [modest_nightingale] - revision: 626a31c169
Running the pipeline on the provided data...
The single-cell data is of rds format and the spatial data is of rds format.
executor >  local (2)
[3f/3e7431] process > runMethods:runNNLS (nnls_test_sp_data) [100%] 1 of 1 ✔
[74/8b5ae2] process > computeMetrics (nnls_test_sp_data)     [100%] 1 of 1 ✔
```

Files pertaining to the runNNLS process can be found in the folder `work/3f/3e7431*`. In particular, `.command.log` contains everything printed from that process. In the base directory, `.nextflow.log` can sometimes provide more info about the entire run as well (old logs are incremented until `.nextflow.log.9` then are overwritten).

(If you do `ls -l 3f/3e7431*`, you can also see that the input data are symbolic links.)

----------------

Thanks again for testing this out. You are actually the first external user of the pipeline, so it is really nice to know where things can be explained better. Your feedback means a lot to us and I will be adding some warnings and more clarifications in the README.

Also apologies for the slightly late reply, I have been sick since I came back from the conference and only got better recently.

Please don't hesitate to report any future issues you come across!
