### ISSUE TITLE
Empty sc_imput when running music

### ISSUE THREAD

**Issue by r-melo** [saeyslab/spotless-benchmark#5]
Hello,

I am trying to run the steps in the quickstart, and I got the following error:
> Error in readRDS(par$sc_input) : unknown input format

To try to debug, in the run_method.nf in the music folder, I added ```echo $sc_input``` on line 19, jut before the Rscript call. Then I got
> No such variable: $sc_input -- Check script './subworkflows/deconvolution/./music/run_method.nf' at line: 19

I am not experienced in nextflow, so I would appreciate directions to fix the issue. 

Thanks!

**Comment by r-melo** [comment]
I added  ```println($sc_input_ch)``` on line 74 of main.nf, right before ```runMethods```. Now the error I get is
> ERROR ~ No such variable: $sc_input_ch

It seems ```Channel.fromPath(params.sc_input)``` is not not working. Any tips on how to troubleshoot that one?

Thanks!

**Comment by csangara** [comment]
Hi, thanks for trying the pipeline!

Based on the first error message, I would guess that the input files are passed to MuSiC, but they are not the correct format. Perhaps they are not  downloaded properly. Can you check that `test_sc_data.rds` is 82.7 MB, and `test_sp_data.rds` is 290 KB?

For the debugging you tried:
- When you added `echo $sc_input`, did you write it within the code block (between the three quotes)?
- To check the contents of the channels of Nextflow, you would need to use the `view()` function, instead of a print statement, so you can type `sc_input_ch.view()` in a separate line.

**Comment by r-melo** [comment]
Hi, thank you for putting the tool together!

That did the trick, I had an incomplete download.

For the debugging:
- It was out of the quotes
- Thank you for the tip

I am not familiar with nexflow yet, I'll probably learn more when trying to include other deconvolution tools.

Thanks!
