### ISSUE TITLE
Error in readRDS(par$sc_input) : unknown input format

### ISSUE THREAD

**Issue by arnoldchang1** [saeyslab/spotless-benchmark#6]
Hello,

Thank you for providing this nextflow pipeline for benchmarking spot deconvolution. I am trying to replicate the results on my system but am coming across this issue when I try to run Music as a test (as shown in the readme):

Here is my command (I have already pulled the relevant docker container (csangara/sp_music):
`nextflow run main.nf -profile local,docker --methods music --sc_input unit-test/test_sc_data.rds --sp_input unit-test/test_sp_data.rds --annot subclass`
And here is the error:
```
[0c/312211] process > runMethods:runMusic (music_test_sp_data) [100%] 1 of 1, failed: 1 ✘
[-        ] process > computeMetrics                           -
WARN: The `echo` directive has been deprecated - use to `debug` instead
ERROR ~ Error executing process > 'runMethods:runMusic (music_test_sp_data)'

Caused by:
  Process `runMethods:runMusic (music_test_sp_data)` terminated with an error exit status (1)

Command executed:

  Rscript /mnt/efs/home/kfb6647/spotless-benchmark/subworkflows/deconvolution/music/script_nf.R
      --sc_input test_sc_data.rds --sp_input test_sp_data.rds             --annot subclass --output pr
oportions_music_test_sp_data             --rootdir /mnt/efs/home/kfb6647/spotless-benchmark
  --sampleID none

Command exit status:
  1

Command output:
  $downsample_cells
  [1] TRUE

  $target_n_cells
  [1] 10000

  $downsample_genes
  [1] TRUE

  $n_hvgs
  [1] 3000

  $pct
  [1] 0.1

  $assay_oi
  [1] "RNA"

  $filter_spots
  [1] "none"
  $sc_input
  [1] "test_sc_data.rds"

  $sp_input
  [1] "test_sp_data.rds"

  $annot
  [1] "subclass"

  $output
  [1] "proportions_music_test_sp_data"

  $rootdir
  [1] "/mnt/efs/home/kfb6647/spotless-benchmark"

  $sampleID
  [1] "none"

  Reading input scRNA-seq reference from test_sc_data.rds

Command error:


  Attaching package: ‘S4Vectors’

  The following objects are masked from ‘package:base’:

      expand.grid, I, unname

  $downsample_cells
  [1] TRUE

  $target_n_cells
  [1] 10000

  $downsample_genes
  [1] TRUE

  $n_hvgs
  [1] 3000

  $pct
  [1] 0.1

  $assay_oi
  [1] "RNA"

  $filter_spots
  [1] "none"

  $sc_input
  [1] "test_sc_data.rds"

  $sp_input
  [1] "test_sp_data.rds"

  $annot
  [1] "subclass"

  $output
  [1] "proportions_music_test_sp_data"

  $rootdir
  [1] "/mnt/efs/home/kfb6647/spotless-benchmark"

  $sampleID
  [1] "none"

  Reading input scRNA-seq reference from test_sc_data.rds
  Error in readRDS(par$sc_input) : unknown input format
  Execution halted
```

**Comment by csangara** [comment]
Hi, thanks for trying the pipeline!

I would guess that the input files are not downloaded properly, as in #5. Can you check locally that test_sc_data.rds is 82.7 MB, and test_sp_data.rds is 290 KB?

**Comment by Chengwei94** [comment]
I am having a similar but different error. I have the checked the rds and its fine.

`Error executing process > 'runMethods:runMusic (music_test_sp_data)'

Caused by:
  Process `runMethods:runMusic (music_test_sp_data)` terminated with an error exit status (1)

Command executed:

  Rscript /home/chengwei/spotless-benchmark/subworkflows/deconvolution/music/script_nf.R             --sc_input test_sc_data.rds --sp_input test_sp_data.rds             --annot subclass --output proportions_music_test_sp_data             --rootdir /home/chengwei/spotless-benchmark             --sampleID none

Command exit status:
  1

Command output:
  $downsample_cells
  [1] TRUE
  
  $target_n_cells
  [1] 10000
  
  $downsample_genes
  [1] TRUE
  
  $n_hvgs
  [1] 3000
  
  $pct
  [1] 0.1
  
  $assay_oi
  [1] "RNA"
  
  $filter_spots
  [1] "none"
  
  $sc_input
  [1] "test_sc_data.rds"
  
  $sp_input
  [1] "test_sp_data.rds"
  
  $annot
  [1] "subclass"
  
  $output
  [1] "proportions_music_test_sp_data"
  
  $rootdir
  [1] "/home/chengwei/spotless-benchmark"
  
  $sampleID
  [1] "none"
  
  Reading input scRNA-seq reference from test_sc_data.rds 

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  /bin/bash: line 0: cd: /scbio4/home/chengwei/spotless-benchmark/work/14/9878745cb7e50474c25373da53f8e2: No such file or directory
  Attaching SeuratObject
  Loading required package: nnls
  Loading required package: ggplot2
  
  Attaching package: ‘BiocGenerics’
  
  The following objects are masked from ‘package:stats’:
  
      IQR, mad, sd, var, xtabs
  
  The following objects are masked from ‘package:base’:
  
      anyDuplicated, append, as.data.frame, basename, cbind, colnames,
      dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
      grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
      order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
      rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
      union, unique, unsplit, which.max, which.min
  
  Welcome to Bioconductor
  
      Vignettes contain introductory material; view with
      'browseVignettes()'. To cite Bioconductor, see
      'citation("Biobase")', and for packages 'citation("pkgname")'.
  
  
  Attaching package: ‘S4Vectors’
  
  The following objects are masked from ‘package:base’:
  
      expand.grid, I, unname
  
  Error in gzfile(file, "rb") : cannot open the connection
  Calls: readRDS -> gzfile
  In addition: Warning message:
  In gzfile(file, "rb") :
    cannot open compressed file 'test_sc_data.rds', probable reason 'No such file or directory'
  Execution halted
  INFO:    Cleaning up image...

Work dir:
  /home/chengwei/spotless-benchmark/work/14/9878745cb7e50474c25373da53f8e2

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line`
