### ISSUE TITLE
Running liver examples

### ISSUE THREAD

**Issue by Chengwei94** [saeyslab/spotless-benchmark#7]
Hi, I am interesting in running the liver experiments but I do not see them in this page? How do I go about running it?

**Comment by csangara** [comment]
Hi,

The liver dataset was downloaded from https://livercellatlas.org/download.php ("MouseStSt, All liver cells" for single-cell data and "MouseStSt, Visium spatial" for spatial data).

The preprocessing script I used is in `scripts/1_preprocess_liver.R` and the evaluation in `scripts/3_evaluate_liver_visium.R`. 
The main thing you have to do for the single-cell data is also download the annotation for the CD45- cells to get the portal/central endothelial cell annotation. I then ran the deconvolution with the [conf/liver_mouse_visium.config config file](https://github.com/saeyslab/spotless-benchmark/blob/main/conf/liver_mouse_visium.yaml). This uses a lot of memory because I ran it on the entire single-cell atlas, but if you subset it to one of the three sequencing approaches - exVivo (this generally gives the best performance), inVivo, Nuc-seq - it should substantially use less memory.

I do realize now that I probably should have uploaded the final files on zenodo as well, as the scripts may be difficult to run. Unfortunately I can only do this after my holiday (Aug 2).

Hope this helps.

**Comment by Chengwei94** [comment]
That would be great if you upload it. I want to benchmark some methods on my own, so it will be best if the procedure is standardized beforehand.

**Comment by csangara** [comment]
Hi, you can find the liver dataset here (`liver_dataset.tar.gz`): https://zenodo.org/record/8211492

There is a `liver_README.txt` inside the file, but I will copy it here:

- liver_mouseStSt* files are the single-cell reference datasets.
- liver_mouseVisium* files are the spatial datasets.

Code used in the paper:
```
nextflow run main.nf -profile hpc --methods rctd -c conf/liver_mouse_visium.config \
# --ref_type #nuclei, inVivo, exVivo, noEC, 9celltypes \
--annot annot_cd45 #options: annot, annot_fine, or annot_cd45 \
--file_type rds #or h5ad \
#--gpu
```

In the paper, we compared four `ref_types`: nuclei, inVivo, exVivo, and 9celltypes. All of them have the same nine cell types making comparison easier.
In supplementary figure S12, we used `--ref_type noEC` for showing deconvolution results with all cell types. This reference filters out endothelial cells that were not annotation zonationally (portal, central, etc).
The reference `liver_mouseStSt_guilliams2022.rds` will be used if no `ref_type` argument is provided, but we do NOT use this in the paper. The file is only provided here for completeness.

We always used `--annot annot_cd45`, but the reference file contains annotation at different levels.
